version: '3'

services:
  db:
    environment:
      POSTGRES_DB: short
      POSTGRES_PASSWORD: short
      POSTGRES_USER: short
    image: postgres:11-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    build: backend
    command: ./wait-for db:5432 -- yarn dev
    tty: true
    environment:
      DATABASE_URL: postgres://short:short@db/short
    volumes:
      - ./backend/src:/usr/src/app/src
    #  - ./backend/test:/usr/src/app/test
    ports:
      - 9000:9000
    #  - 5858:5858
    depends_on:
      - db

volumes:
  dbdata:
